### ISSUE TITLE
Deploy the Django app to AKS

### ISSUE THREAD

**Issue by MgenGlder** [dearborn-coding-club/website-base-backend#10]
## Summary
Now that we've decided on a hosting platform to use for our Django service, we'll need to deploy it up and see it in action. In https://github.com/dearborn-coding-club/website-base-backend/issues/5, we decided to go with AKS (Azure Kubernetes Service) as the tool we would use to host and deploy the service. 

Last week we took a look at configuring an AKS instance and ran into a couple of hiccups. With the lessons learned, we should continue working towards setting this up. In the end, we'd like to have a dearborncodingclub.com point to the Django app hosted in AKS.

### Tasks
- [ ] Create an AKS cluster that can host our Kubernetes deployments of the Django app.
- [ ] Deploy the Django app to the AKS cluster
- [ ] Add CNAME registry mapping to the domain registrar to connect the site to the AKS cluster and let the magic happen :tada:

**Comment by MgenGlder** [comment]
I haven't had much time to look at this during the week, but I'll plan to get this sorted out tomorrow during our `Code and Hang` session.
